default_stages: [push]
default_language_version:
  python: python3.8
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: check-ast
    stages: [commit, push]
    name: Check python ast
    description: Simply check whether the files parse as valid python.
    entry: check-ast
    language: python
    types: [python]
  - id: debug-statements
    stages: [commit, push]
    name: Debug Statements (Python)
    description: Check for debugger imports and py37+ `breakpoint()` calls in python source.
    entry: debug-statement-hook
    language: python
    types: [python]
  - id: check-yaml
    stages: [commit, push]
    name: Check Yaml
    description: This hook checks yaml files for parseable syntax.
    entry: check-yaml
    language: python
    types: [yaml]
  - id: check-json
    stages: [commit, push]
    name: Check JSON
    description: This hook checks json files for parseable syntax.
    entry: check-json
    language: python
    types: [json]
  - id: check-merge-conflict
    stages: [commit, push]
    name: Check for merge conflicts
    description: Check for files that contain merge conflict strings.
    entry: check-merge-conflict
    language: python
    types: [text]
  - id: mixed-line-ending
    stages: [commit, push]
    name: Mixed line ending
    description: Checks mixed line ending
    entry: mixed-line-ending
    language: python
    types: [text]
    args: [--fix=no]
  - id: end-of-file-fixer
    name: Fix End of Files
    description: Ensures that a file is either empty, or ends with one newline.
    entry: end-of-file-fixer
    language: python
    types: [text]
    stages: [commit, push, manual]
- repo: local
  hooks:
  - id: flake8
    stages: [commit, push]
    name: flake8
    entry: poetry run flake8 core
    language: system
    pass_filenames: false #https://github.com/pre-commit/pre-commit/issues/836
  - id: black
    stages: [commit, push]
    name: black
    entry: poetry run black --skip-string-normalization core
    language: system
    args: ['--check']
    pass_filenames: false
  - id: bandit
    stages: [commit, push]
    name: Bandit
    entry: poetry run bandit -r core -l --recursive -x "*/tests/*" -o ./report/security.log --quiet
    language: system
    pass_filenames: false
  - id: mypy
    stages: [commit, push]
    name: Mypy
    entry: poetry run mypy
    language: system
    pass_filenames: false
